server:
  port: 8081

spring:
  application:
    name: produtos-api
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
